spring.application.name=vendor-management-system


# ---------------- JSP CONFIGURATION ----------------

spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp



# ---------------- DATABASE CONFIGURATION ----------------

spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://localhost:5432/vendor_management

spring.datasource.username=postgres

spring.datasource.password=Abirdas@1999



# ---------------- HIBERNATE CONFIGURATION ----------------

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.format_sql=true



# ---------------- SERVER PORT ----------------

server.port=8082



# ---------------- SPRING SECURITY ----------------

spring.security.user.name=abir

spring.security.user.password=123



# GITHUB OAUTH

spring.security.oauth2.client.registration.github.client-id=Ov23lizd2cULRtvlwAS2

spring.security.oauth2.client.registration.github.client-secret=c057334694ad9a7a0360e5a5052c940db0640899